# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - mca-d-web-1

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Create env file
      run: |
          touch .env
          echo AZURE_BLOB_IMAGE_URL="${{AZURE_BLOB_IMAGE_URL}}" >> .env
          echo AZURE_STORAGE_CONNECTION_STRING=${{AZURE_STORAGE_CONNECTION_STRING}} >> .env
          echo CLIENT_SECRET=${{CLIENT_SECRET}} >> .env
          echo DATAVERSE_API_BASE_URL=${{DATAVERSE_API_BASE_URL}} >> .env
          echo DATAVERSE_API_SERVICE_URL=${{DATAVERSE_API_SERVICE_URL}} >> .env
          echo DB_POST_URL=${{DB_POST_URL}} >> .env
          echo REFERENCE_GENERATOR_KEY=${{REFERENCE_GENERATOR_KEY}} >> .env
          echo REFERENCE_GENERATOR_URL=${{REFERENCE_GENERATOR_URL}} >> .env
          echo TENANT_ID=${{TENANT_ID}} >> .env
          cat .env

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mca-d-web-1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_513dee18fa4b4460879379b66b0cacf2 }}
        package: .
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
